# Change these first
owner: xibosignage # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: Xibo Signage Website
    url: https://xibo.org.uk
  - name: Xibo Signage Customer Portal
    url: https://app.xibo.org.uk
  - name: Xibo Signage Blog
    url: https://blog.xibo.org.uk
  - name: Xibo Adspace Website
    url: https://xibo-adspace.com

assignees:
  - alexharrington

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status-page
  logoUrl: https://raw.githubusercontent.com/xibosignage/status-page/master/assets/xibo-logo.png
  name: Xibo Signage Service Status
  introTitle: "Xibo Service Status"
  introMessage: All latencies are measures from west-coast US and are not indicative of local latency from your location
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
