# Change these first
owner: xibosignage # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: Xibo Signage Website
    url: https://xibo.org.uk
  - name: Xibo Cloud United Kingdom/London
    url: $CLOUD_GB_URL
  - name: Xibo Cloud CDN United Kingdom/London
    url: $CLOUD_GB_CDN_URL
  - name: Xibo Cloud United States/New York
    url: $CLOUD_NYC_URL
  - name: Xibo Cloud CDN United States/New York
    url: $CLOUD_NYC_CDN_URL
  - name: Xibo Cloud Germany/Frankfurt
    url: $CLOUD_DEU_URL
  - name: Xibo Cloud CDN Germany/Frankfurt
    url: $CLOUD_DEU_CDN_URL
  - name: Xibo Cloud Singapore/Singapore
    url: $CLOUD_SGP_URL
  - name: Xibo Cloud CDN Singapore/Singapore
    url: $CLOUD_SGP_CDN_URL
  - name: Xibo Cloud Australia/Sydney
    url: $CLOUD_AUS_URL
  - name: Xibo Cloud CDN Australia/Sydney
    url: $CLOUD_AUS_CDN_URL
  - name: Xibo Signage Customer Portal
    url: https://app.xibo.org.uk
  - name: Xibo Player License Service
    url: $PLAYER_LICENSE_URL
  - name: Xibo Signage Blog
    url: https://blog.xibo.org.uk
  - name: Xibo Adspace Website
    url: https://xibo-adspace.com


assignees:
  - alexharrington

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status-page
  logoUrl: https://raw.githubusercontent.com/xibosignage/status-page/master/assets/xibo-logo.png
  name: Xibo Signage Service Status
  introTitle: "Live Service Status"
  introMessage: All latencies are measured from mainland United States and are not indicative of local latency from your location. If you are having an issue and all services are up and running, please open a ticket with our support team who can assist you.
  navbar:
    - title: Status
      href: /
    - title: Support
      href: https://xibo.org.uk/help

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
